### PR TITLE
Deep merge of browser options

### PR DESCRIPTION
**Pull request by Ado77**
Made the browser options do a deep clone instead of a shallow one to allow more options through

### CODE REVIEW

**Comment by random82** [comment]
That will allow overriding default wct-local options from the plugin configuration

**Comment by Ado77** [comment]
I know everyone is focused on the new version of the components but this would unblock our CI pipeline... Is there any chance  :smile_cat: @notwaldorf :smile_cat:, @justinfagnani or @rictic could have a quick look?

/End of long winded bump

**Comment by justinfagnani** [comment]
I'll take a look

**Comment by notwaldorf** [comment]
Hah, thanks for the extra cat emoji! (I'm useless at wct so I can't help though)

**Pull request merged**
