### PR TITLE
Remove reliance on document.currentScript

### PR DESCRIPTION
**Pull request by usergenic**
- Removing recently added dependency on `document.currentScript` which is unavailable in IE11
 - Fixes https://github.com/Polymer/web-component-tester/issues/602
 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by rictic** [comment]
So, this is a change in behavior though, yeah?

**Comment by rictic** [comment]
Instead of loading wct's browser.js with an `npm` query param, now the toplevel page needs to be loaded with the `npm` query param. Is this documented somewhere? I think it should definitely be in the changelog.

**Comment by usergenic** [comment]
@rictic I added behavior that checked for "npm mode" by incorrectly choosing to use document.currentScript -- That check itself breaks in IE11 and people that could care less about npm mode are effected.

**Comment by usergenic** [comment]
The top-level page is loaded with the npm query param by wct.  That behavior already happened.

**Comment by usergenic** [comment]
I'll put the note in the changelog, but we havent really covered anything wrt npm testing with wct yet... That is forthcoming

**Comment by rictic** [comment]
So previously you would both load the toplevel page with `?npm=true` and you would load browser.js as `browser.js?npm=true`?

**Comment by rictic** [comment]
Ah ok, yeah a line in the changelog is enough then. I'm not sure I 100% get the change, but I'm not blocking this PR from landing.

**Pull request merged**
