### PR TITLE
New: Add version flag to CLI

### LINKED ISSUE #198: --version and -v missing
Guys can you add -v and --version flag to wct

### PR DESCRIPTION
**Pull request by stramel**
Fixes #198 

 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by stramel** [comment]
@usergenic So I hacked around a bit and got the builds passing again... :grimacing: I can revert if you would prefer.

**Comment by gmcdev** [comment]
@stramel - I haven't used TS before, but I'm trying to submit a PR on this issue:
https://github.com/Polymer/web-component-tester/issues/561

However, I'm unable to build this project, out-of-the-box....but it looks like you're getting it to compile. Can you give me any pointers? Thank you!

**Comment by stramel** [comment]
@gmcdev You can use `npm run prepublish` to build and test. This won't do the typescript linting though.

I haven't really used TS much either. The build is failing for everything across the board right now. I did a lot of hacky things related to some type definitions that are incorrect. I'm waiting for @usergenic to let me know if this is going to be okay or not. I would suggest sticking to the command above for now.

**Comment by stramel** [comment]
@usergenic Moved it out into a separate PR for ease. #571

**Comment by stramel** [comment]
Rebased onto master with green build, changelog and tests.

**Comment by usergenic** [comment]
@stramel I'm bringing this into a branch `add-versions` so I can add the arg to the config and handle it using the parser.

**Comment by stramel** [comment]
@usergenic That sounds good, was just basing it off of the `polymer-cli`.

https://github.com/Polymer/polymer-cli/blob/5d0645e00b450747b55619363113e93df71c3bf6/src/polymer-cli.ts#L143-L148

**Pull request merged**
