### PR TITLE
Update lodash to version 4.0.0

### PR DESCRIPTION
**Pull request by hypnoce**

### CODE REVIEW

**Comment by MartinMoizard** [comment]
LGTM :)

**Comment by azakus** [comment]
Not sure why the tests didn't run, but this broke *all* the tests. lodash 4 has some significant api changes that would need to be addressed.

**Comment by MartinMoizard** [comment]
I am okay with these commits being contributed to Google.

**Comment by MartinMoizard** [comment]
CLA signed

**Comment by hypnoce** [comment]
@MartinMoizard  will make a new one with proper cla.

**Comment by MartinMoizard** [comment]
The valid PR is here https://github.com/Polymer/web-component-tester/pull/277

**Pull request closed without merging**
