### PR TITLE
Updated dependencies

### LINKED ISSUE #567: Upgrade sinon to latest v2.3.4
If possible please upgrade sinon to ^2.3.0.
A lot of important functionality has been added, like native promise support and much more.

### PR DESCRIPTION
**Pull request by stramel**
- [x] CHANGELOG.md has been updated

- Major upgraded async, chai, findup-sync, sinon, socket.io, and update-notifier.
- Upgraded to latest on all other dependencies and optional dependencies.
- Upgraded `@types/node`

Fixes #567 

**TODO:**

- [x] cleankill 2.0.0 bump

### CODE REVIEW

**Comment by stramel** [comment]
Rebased onto master with green build, changelog and tests updated.

Still not sure on `cleankill v2`

**Comment by stramel** [comment]
Rebased onto master with green build, changelog and tests updated.

**Comment by stramel** [comment]
@usergenic Updated to contain the latest changes.

**Comment by stramel** [comment]
@usergenic I rebased this. Anything else I need to do?

**Comment by usergenic** [comment]
@stramel checking this out right now.

**Comment by stramel** [comment]
Thanks! :smile:

**Pull request merged**
