### PR TITLE
Fixes #547 : --webserver-port option doesn't change the actual port

### LINKED ISSUE #547: --webserver-port option doesn't change the actual port
I am using version 6.0.0 and when trying to change the webserver port using the `--webserver-port` argument is still remains 8081 as the default `polymer serve` port.

### PR DESCRIPTION
**Pull request by c-okelly**
Fixes #547. Ensure that the correct default value used when user does not set the port.

 - [ x ] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by c-okelly** [comment]
I signed it!

**Comment by krumware** [comment]
also need this 👍

**Comment by c-okelly** [comment]
Hey @aomarks,

I noticed that you have approved some of the other pull requests in this repo. Was wondering if you would be able to give me any feedback on what might need be required to get approval for this pr.

Please let me know if you would like any changes made.

Thanks in advance,

Conor

**Comment by justinfagnani** [comment]
@c-okelly this PR looks good, but we're going to need it ported over to the new Polymer/tools monorepo. We've been busy with the mirgration, and haven't automatically moved issues and PRs yet.

**Comment by c-okelly** [comment]
@justinfagnani Thanks for the reply. Let me know if there is anything I can do to help.

**Comment by justinfagnani** [comment]
You can certainly open a PR against Polymer/tools

**Comment by aomarks** [comment]
Closing this pull request because this repo is now archived. If this PR is still active, please submit a new one at https://github.com/Polymer/tools.

**Pull request closed without merging**
