### PR TITLE
Use hostname instead of `localhost`

### PR DESCRIPTION
**Pull request by usergenic**
- [x] CHANGELOG.md has been updated
 - Fixes https://github.com/Polymer/web-component-tester/issues/523
 - BEFORE MERGING: Need to verify that WCT continues to work in situations where a call to `address().address` may return '::' for ipv6 scenarios.

### CODE REVIEW

**Comment by hvdb** [comment]
Any News?

**Comment by usergenic** [comment]
@hvdb is almost ready but there's no test coverage for this yet so i still need to add those.  will do soon.

**Comment by saeidzebardast** [comment]
any news?

**Comment by justinfagnani** [comment]
Claing in favor of #647

**Pull request closed without merging**
