### PR TITLE
Forward proxy config to the polyserve

### PR DESCRIPTION
**Pull request by tomalec**
`proxy-path` and `proxy-target`

https://github.com/Polymer/web-component-tester/issues/607

 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by usergenic** [comment]
@tomalec This is great.  Ideally, I'd like to add a test before merging to master, so I'm going to modify PR to merge to a separate branch first before adding test.

**Comment by tomalec** [comment]
@usergenic So it's not yet merged to the master, is it? Should I add tests to `tomalec:forward-proxy-config ` branch?

**Comment by tomalec** [comment]
Is there any similar test for nested props? As when I tried:
```ts
      it('honors proxy: {path, target}', async () => {
        process.chdir(path.join(ROOT, 'proxied'));

        const options = (await expectRun([])).options;
        expect(options.proxy).to.exist;
        // ...
```
It fails to compile with `tsc` before the fix, as 
```
test/unit/cli.ts(117,22): error TS2339: Property 'proxy' does not exist on type
'Config'.
```

**Comment by tomalec** [comment]
Also, is there a reason to use `chai^3.5.0` - latest is `4.2.1` and allows nice `have.nested.property` assertions.

But what is most important, I have no idea how to get any reference to actual polyserve server being run, to check if it received the proxy config.

**Comment by usergenic** [comment]
@tomalec sorry for confusion.  you can follow the progress of the merge here: https://github.com/Polymer/web-component-tester/pull/643

A `master` merge is pending a CI run right now after some seemingly unrelated recent issues with typescript strictness.

**Pull request merged**
