### PR TITLE
Update Mocha to patch critical security issue

### LINKED ISSUE #723: Failing npm audit
=== npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.10.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wct-browser-legacy [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wct-browser-legacy > mocha > growl                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/146                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wct-browser-legacy [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wct-browser-legacy > lodash                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wct-browser-legacy [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wct-browser-legacy > stacky > lodash                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ wct-browser-legacy [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ wct-browser-legacy > mocha > debug                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

### PR DESCRIPTION
**Pull request by intcreator**
Fixes #723.

### CODE REVIEW

**Comment by intcreator** [comment]
I signed it!

**Comment by web-padawan** [comment]
The project has moved to the [tools](https://github.com/Polymer/tools/tree/master/packages/web-component-tester) repo and the Mocha is already upgraded there.

**Comment by intcreator** [comment]
@web-padawan good to know.  It looks like modulizer is putting in a reference to this repo in my package.json:

```
  "devDependencies": {
    "wct-browser-legacy": "^1.0.1"
  }
```

So does that mean modulizer needs a patch?

**Comment by intcreator** [comment]
Looks like this is being addressed by Polymer/tools#533

**Pull request closed without merging**
