### PR TITLE
fix(dep): Update polyserve dep

### LINKED ISSUE #690: npm ERR! 404 Not Found: @types/escodegen@^0.0.2
I am struggling with this issue trying to install web-component-tester.
`npm install -g web-component-tester `

`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! code E404
npm ERR! 404 Not Found: @types/escodegen@^0.0.2`

Any clue why ?

### PR DESCRIPTION
**Pull request by tverhoken**
_polyserve@0.25.2_ pulls the escodegen typing dependency that causes troubles during dependencies installation.

Closes #690

 - [ ] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by tverhoken** [comment]
I signed it!

**Comment by tlalaux** [comment]
Should be good!

**Comment by tverhoken** [comment]
I signed it!

**Comment by aomarks** [comment]
Closing this pull request because this repo is now archived. If this PR is still active, please submit a new one at https://github.com/Polymer/tools.

**Pull request closed without merging**
